services:
  es01:
    image: ubuntu-systemd:rk-lab
    pull_policy: never
    hostname: es01
    container_name: es01
    privileged: true
    environment:
      - NODE_NAME=es01
    volumes:
      - es01_data:/var/lib/elasticsearch
      - es01_conf:/etc/elasticsearch
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./es-backups:/usr/share/elasticsearch/backup
    ports:
      - "9200:9200"   # expose ES01 on localhost
    networks:
      - esnet
    tmpfs:
      - /run
      - /run/lock

  es02:
    image: ubuntu-systemd:rk-lab
    pull_policy: never
    hostname: es02
    container_name: es02
    privileged: true
    environment:
      - NODE_NAME=es02
    volumes:
      - es02_data:/var/lib/elasticsearch
      - es02_conf:/etc/elasticsearch
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./es-backups:/usr/share/elasticsearch/backup
    ports:
      - "9201:9200"   # expose ES02 on localhost
    networks:
      - esnet
    tmpfs:
      - /run
      - /run/lock


  # Logstash setup:
  # - Place pipeline configs under ./logstash/pipeline/
  #   (01_input.conf, 02_filter.conf, 03_output.conf, dead_letter_indexing_pipeline.conf)
  # - Place logstash.yml under ./logstash/config/
  # - Download PostgreSQL JDBC driver as ./logstash/postgresql.jar
  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.1
    container_name: logstash
    depends_on:
      - es01
      - es02
    environment:
      - ES_HOSTS=http://es01:9200 http://es02:9200
      - DATA_STORE_URL=jdbc:postgresql://postgres:5432/testdb
      - DATA_STORE_USER=testuser
      - DATA_STORE_PASS=password
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash/postgresql.jar:/usr/share/logstash/ccd/postgresql.jar
    ports:
      - "5044:5044"   # expose Logstash on localhost
    networks:
      - esnet

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - esnet


  es01-init:
    image: alpine:3
    depends_on:
      - es01
    volumes:
      - ./init-watermark.sh:/init.sh:ro
    entrypoint: ["/bin/sh", "-c"]
    command: "/init.sh"
    restart: "no"
    networks:
      - esnet

volumes:
  es01_data:
  es01_conf:
  es02_data:
  es02_conf:
  pg_data:

networks:
  esnet:
    driver: bridge
